Code/IdeasGroup/IdeasGroup/Controllers/IdeasGroupController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IdeasGroup.Domain;
using IdeasGroup.Models;

namespace IdeasGroup.Controllers
{
    public partial class IdeasGroupController : Controller
    {
        private readonly IIdeasGroupRepository _repository;

        //Si vous n'utilisez pas d'IOC, utilisez au moins la méthode
        //du POOR MANs DI : 
        //On fournit directement une version de l'implémentation
        //à utiliser avec le constructeur par défaut:
        //public IdeasGroupController() : this(new IdeaGroupRepository())
        //{ 
        //}

        public IdeasGroupController(IIdeasGroupRepository repository)
        {
            _repository = repository;
        }

        public virtual ActionResult Index()
        {
            var ideas = _repository
                .GetAll()
                .Select(idea => (IdeaListItem)idea);

            return View(ideas);
        }

        public virtual ActionResult Details(int id)
        {
            var idea = _repository.Find(x => x.Id == id);
            return View(idea);
        }

        [HttpGet]
        public virtual ActionResult Create()
        {
            var idea = new IdeaEditModel();
            return View(idea);
        } 

        [HttpPost]
        public virtual ActionResult Create(IdeaEditModel idea)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repository.Save(idea.MergeTo(new Idea()));
                }
                else
                {
                    throw new InvalidDataException();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(idea);
            }
        }
        
        [HttpGet]
        public virtual ActionResult Edit(int id)
        {
            var i = _repository.Find(x => x.Id == id);
            if(i==null)
                return RedirectToAction("Index");

            var ideaModel = new IdeaEditModel(i.Id, i.Title, i.Detail, i.Published, i.Author);
            return View(ideaModel);
        }

        [HttpPost]
        public virtual ActionResult Edit(IdeaEditModel idea)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var trackedItem = _repository.Find(x => x.Id == idea.Id);
                    if(trackedItem == null)
                        throw new InvalidDataException();

                    _repository.Save(idea.MergeTo(trackedItem));
                }
                else
                {
                    throw new InvalidDataException();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View(idea);
            }
        }

        [HttpGet]
        public virtual ActionResult Delete(int id)
        {
            var idea = _repository.Find(x => x.Id == id);
            return View(idea);
        }

        [HttpPost]
        public virtual ActionResult Delete(Idea idea)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repository.Delete(idea);
                }
                else
                {
                    throw new InvalidDataException();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Code/IdeasGroup/IdeasGroup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.20.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>Student Suggest ::</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Ideas","Index","IdeasGroup")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

Code/IdeasGroup/IdeasGroup/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}